branch-defaults:
  default:
    environment: django-env
    group_suffix: null
global:
  application_name: LocationPetches
  branch: null
  default_ec2_keyname: LocationPetches
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
