# Generated by Django 4.0.3 on 2023-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_site',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='comment_site',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment_site',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment_site',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
