# Generated by Django 4.0.3 on 2023-01-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_utilisateur_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='slug',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='Inconnu', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password2',
            field=models.CharField(default='Inconnu', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
