# Generated by Django 4.0.3 on 2023-01-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_utilisateur_slug_utilisateur_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='password',
            new_name='password1',
        ),
    ]
