# Generated by Django 4.0.3 on 2023-01-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_rename_password_utilisateur_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
